[package]
name = "whos-home"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "*"
aws-sdk-sqs = "*"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
